#Kaggle_Bike Sharing Demand
#Description--
#Bike sharing systems are a means of renting bicycles where the process of obtaining membership, rental, and bike return is automated via a network of kiosk locations throughout a city. Using these systems, people are able rent a bike from a one location and return it to a different place on an as-needed basis. Currently, there are over 500 bike-sharing programs around the world.
#The data generated by these systems makes them attractive for researchers because the duration of travel, departure location, arrival location, and time elapsed is explicitly recorded. Bike sharing systems therefore function as a sensor network, which can be used for studying mobility in a city. In this competition, participants are asked to combine historical usage patterns with weather data in order to forecast bike rental demand in the Capital Bikeshare program in Washington, D.C.

#You are provided hourly rental data spanning two years. For this competition, the training set is comprised of the first 19 days of each month, while the test set is the 20th to the end of the month. You must predict the total count of bikes rented during each hour covered by the test set, using only information available prior to the rental period.

#I am trying to predict the 'count'.
#Exploratory Data Analysis
#Scatterplot of count vs temperature
g1 <- ggplot(bikeshare,aes(temp,count)) + geom_point(size=3,alpha=0.2, aes(color=temp)) + theme_hc() + labs(x='Temperature (C)',y='# of Rentals')
print(g1)
#Looks like the maximum rentals peak at ~27-29C.

#Plot count versus datetime as a scatterplot with a color gradient based on temperature. 
bikeshare$datetime <- as.POSIXct(bikeshare$datetime)
g2 <- ggplot(bikeshare,aes(datetime,count)) + geom_point(aes(color=temp),alpha=0.5)  + scale_color_continuous(low='#f41313',high='#2623ef') +theme_hc()
print(g2)

#Two things: Their appears to be a seasonality to the data, winter & summer. Also that bike rental counts are increasing in general. This may present a problem with using a linear regression model if the data is non-linear.

#Correlation btw temp and count
cor(bikeshare[,c('temp','count')])

#exploration of seasonal data. 
#season- 1 = spring, 2 = summer, 3 = fall, 4 = winter
g3 <- ggplot(bikeshare,aes(factor(season),count)) + geom_boxplot(aes(color=factor(season))) + theme_hc()
print(g3)

#The data suggests there are more rentals in winter than in spring, however, a non-linear relationship exists btw count & temp, in addition to issues with the general growth of rental popularity. Thus, the popularity of bike rentals isn't based on the season!

#Created an "hour" column that takes the hour from the datetime column. 
bikeshare$hour <- sapply(bikeshare$datetime, function(x){format(x,"%H")})
bikeshare$hour <- sapply(bikeshare$hour,as.numeric)
print(bikeshare)

#Now create a scatterplot of count versus hour, with color scale based on temp. Only use bike data where workingday==1
p1 <- ggplot(filter(bikeshare,workingday==1), aes(hour,count))
p2 <- p1 + geom_point(position = position_jitter(w=1, h=0),aes(color=temp),alpha=0.5)
p3 <- p2 + scale_color_gradientn(colors = c('dark blue','blue','light blue','light green','yellow','orange','red'))
p4 <- p3 + theme_hc() + ggtitle('Working Day Bike Rentals')
print(p4)

#Now create the same plot for non working days:
p5 <- ggplot(filter(bikeshare,workingday==0), aes(hour,count))
p6 <- p1 + geom_point(position = position_jitter(w=1, h=0),aes(color=temp),alpha=0.8)
p7 <- p2 + scale_color_gradientn(colors = c('dark blue','blue','light blue','light green','yellow','orange','red'))
p8 <- p3 + theme_hc() + ggtitle('Non-working day Rentals')
print(p8)

#notice that working days have peak activity during the morning (~8am) and right after work gets out (~6pm), with some lunchtime activity. While the non-work days have a steady rise and fall after ~7pm.

#Building the Linear Model
#Use lm() to build a model that predicts count based solely on the temp feature, name it temp.model
temp.model <- lm(count~temp,bikeshare)
summary(temp.model)

temp.test <- data.frame(temp=c(25))
predict(temp.model,temp.test)

model <- lm(count ~ . -casual -registered -datetime -atemp,bikeshare)
summary(model)

#Did the model perform well on the training data? 
#A linear model like the one I chose which uses OLS won't be able to take into account seasonality of the data, and will get thrown off by the growth in the dataset, accidentally attributing it towards the winter season, instead of realizing its just overall demand increasing! In conclusin, this sort of model doesn't work well with seasonal and time series data. 










